# Generated by Django 4.2.3 on 2023-08-10 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdepartments',
            name='department',
            field=models.CharField(default=None, error_messages={'unique': 'Este departamento já existe'}, help_text='Mínimo 5 caracteres', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='applicationjobpositions',
            name='jobposition',
            field=models.CharField(default=None, help_text='Mínimo 5 caracteres', max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='jobposition'),
        ),
        migrations.AlterField(
            model_name='applicationpeoples',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Este cpf já existe'}, help_text='Only numbers', max_length=14, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='applicationpeoples',
            name='department',
            field=models.ForeignKey(default=None, help_text='Informe departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.applicationdepartments', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='applicationpeoples',
            name='fullname',
            field=models.CharField(default=None, help_text='Mínimo 5 caracteres', max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='applicationpeoples',
            name='jobposition',
            field=models.ForeignKey(default=None, help_text='Informe cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.applicationjobpositions', verbose_name='job position'),
        ),
        migrations.AlterField(
            model_name='applicationpermissions',
            name='jobposition',
            field=models.ForeignKey(default=None, help_text='Informe permissão', on_delete=django.db.models.deletion.CASCADE, to='app.applicationjobpositions', verbose_name='permission'),
        ),
    ]
